services:
  alloy:
    volumes:
      - ./alloy/config/config.alloy:/etc/alloy/config.alloy
      - ./alloy/data:/var/lib/alloy/data
    ports:
      - 12345:12345
    image: grafana/alloy:latest
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
